### ISSUE TITLE
404 Page Not Found : Invalid / Non-existant token id

### ISSUE THREAD

**Issue by PhillypHenning** [conradludgate/terraform-provider-spotify#25]
Hey - I'm following your blog and can't seem to get a a successful query using your provider.

I'm using a self hosted Auth Proxy and have authenticated;
```
 % docker run --rm -it -p 27228:27228 --env-file ./.env ghcr.io/conradludgate/spotify-auth-proxy
APIKey:   qoYoZ-_ouqBGi7cFslJw8Ilpe9xRPHn7qe3ytPQIxxK4tTrnGrai7VGWL7mdjvlb
Auth URL: http://localhost:27228/authorize?token=QQQDuc8UIw-5Og6DmWhzdQJKbzhOxtbTEPQsN89KcjejJ4ctEInpiJ78q8fO0tl_
Authorization successful
```

However, when I run the Terraform Apply command I'm met with;
```
│ Error: could not perform search [[artist:"Dolly Parton"]]: Get "https://api.spotify.com/v1/search?limit=10&q=artist%3A%22Dolly+Parton%22&type=track": 404 page not found
│ 
│ 
│   with data.spotify_search_track.by_artist,
│   on main.tf line 36, in data "spotify_search_track" "by_artist":
│   36: data "spotify_search_track" "by_artist" {
```

Taking the URL that was spat out above results in;
```
{
    "error": {
        "status": 401,
        "message": "No token provided"
    }
}
```

By adding in a Bearer token (Generated through the Dev Console of Spotify) I finally get results to print to POSTMAN, but I don't see anything in your doc that would suggest I could use my bearer token... 

Any thoughts?

**Comment by conradludgate** [comment]
Can I see your terraform files? You should be setting the api_key field in the provider configuration to the one the docker container gave you

```tf
provider "spotify" {
  api_key = "qoYoZ-_ouqBGi7cFslJw8Ilpe9xRPHn7qe3ytPQIxxK4tTrnGrai7VGWL7mdjvlb"
}
```

(or you can omit that section, and terraform should prompt you for the api key)

**Comment by PhillypHenning** [comment]
main.tf
```
# Configuration for Terraform
terraform {
  required_providers {
    spotify = {
      version = "~> 0.1.5"
      source  = "conradludgate/spotify"
    }
  }
}

# Configure "Spotify" community provider
provider "spotify" {
  api_key = var.spotify_api_key
}

# Defined in the terraform.tfvars files
variable "spotify_api_key" {
  type = string
}

resource "spotify_playlist" "playlist" {
  name        = "Terraform Summer Playlist"  
  description = "This playlist was created by Terraform"  
  public      = true
  
  tracks = [    
    data.spotify_search_track.by_artist.tracks[0].id,    
    data.spotify_search_track.by_artist.tracks[1].id,    
    data.spotify_search_track.by_artist.tracks[2].id,  
  ]
}

data "spotify_search_track" "by_artist" {
  artists = ["Dolly Parton"]

  #  album = "Jolene"  
  #  name  = "Early Morning Breeze"
}

output "spotify_api_key"{
  value = var.spotify_api_key
}

output "playlist_url" {  
  value       = "https://open.spotify.com/playlist/${spotify_playlist.playlist.id}"  
  description = "Visit this URL in your browser to listen to the playlist"
}
```

terraform.tfvars
```
spotify_api_key     = "Super Secret.. Shhh"
```
I had my AWS credentials in my ENV prior, but I also ran the aws configure just to be safe to no results.

**Comment by conradludgate** [comment]
Probably worth updating the version to `0.2.2`, a few bugs have been fixed since then

**Comment by PhillypHenning** [comment]
You'll want to update your blog as well if that's the case!

**Comment by conradludgate** [comment]
It's not my blog! It's from Hashicorp (I am unaffiliated with them)

**Comment by PhillypHenning** [comment]
Alright - Changing to use 0.2.2 did solve the first issue (or at least made it more verbose) but I'm still seeing a similar issue; 
I've made sure to Authenticate using the spotify-auth-proxy;
```
% docker run --rm -it -p 27228:27228 --env-file ./.env ghcr.io/conradludgate/spotify-auth-proxy
APIKey:   ...
Auth URL: http://localhost:27228/authorize?token=...
Authorization successful
```
However, when I run Terraform Apply;
```
│ Error: could not perform search [[artist:Dolly Parton]]: Get "https://api.spotify.com/v1/search?limit=10&q=artist%3ADolly+Parton&type=track": APIToken: invalid authorization
│ 
│ 
│   with data.spotify_search_track.by_artist,
│   on main.tf line 33, in data "spotify_search_track" "by_artist":
│   33: data "spotify_search_track" "by_artist" {
```

**Comment by PhillypHenning** [comment]
> It's not my blog! It's from Hashicorp (I am unaffiliated with them)

Dang those guys sending all the traffic at you like this ;)

**Comment by conradludgate** [comment]
Hmm. That error occurs when the API Key is wrong. Maybe double check it (it changes every time you run the docker container) or you can add `SPOTIFY_PROXY_API_KEY=MY_FIXED_API_KEY` to your env file

**Comment by PhillypHenning** [comment]
That did the trick! 
Thanks Conrad :)
